apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nats
spec:
  generators:
    - git:
        repoURL: https://github.com/Viva-con-Agua/nats-deploy.git
        revision: main
        directories:
          - path: stages/*
  template:
    metadata:
      name: "nats-{{path.basename}}"
    spec:
      destination:
        name: in-cluster
      project: "vca-{{path.basename}}"
      source:
        repoURL: https://github.com/Viva-con-Agua/nats-deploy.git
        targetRevision: main
        path: "{{path}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
