apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
    name: base
spec:
    generators:
        - git:
              repoURL: https://github.com/Viva-con-Agua/base-frontend-template-deploy.git
              revision: HEAD
              directories:
                  - path: '*'
    template:
        metadata:
            name: 'base-{{path}}'
        spec:
            destination:
                name: in-cluster
            project: 'vca-{{path}}'
            source:
                repoURL: https://github.com/Viva-con-Agua/base-frontend-template-deploy.git
                targetRevision: HEAD
                path: '{{path}}'
                kustomize:
                    version: kustomize5
            syncPolicy:
                automated:
                    prune: false
                    selfHeal: false
