apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: geo-server
spec:
  generators:
    - git:
        repoURL: https://github.com/Viva-con-Agua/geo-server-deploy.git
        revision: HEAD
        directories:
          - path: "*"
  template:
    metadata:
      name: "geo-server-{{path}}"
    spec:
      destination:
        name: in-cluster
      project: "vca-{{path}}"
      source:
        repoURL: https://github.com/Viva-con-Agua/geo-server-deploy.git
        targetRevision: HEAD
        path: "{{path}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
