apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
    name: mediawiki
spec:
    generators:
        - git:
              repoURL: https://github.com/Viva-con-Agua/mediawiki-deploy.git
              revision: HEAD
              directories:
                  - path: "*"
    template:
        metadata:
            name: "mediawiki-{{path}}"
        spec:
            destination:
                name: in-cluster
            project: "vca-{{path}}"
            source:
                repoURL: https://github.com/Viva-con-Agua/mediawiki-deploy.git
                targetRevision: HEAD
                path: "{{path}}"
                kustomize:
                    version: kustomize5
            syncPolicy:
                automated:
                    prune: true
                    selfHeal: true
