apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: payment-form
spec:
  generators:
    - git:
        repoURL: https://github.com/Viva-con-Agua/payment-form-deploy.git
        revision: HEAD
        directories:
          - path: "*"
  template:
    metadata:
      name: "payment-form-{{path}}"
    spec:
      destination:
        name: in-cluster
      project: "vca-{{path}}"
      source:
        repoURL: https://github.com/Viva-con-Agua/payment-form-deploy.git
        targetRevision: HEAD
        path: "{{path}}"
        kustomize:
          version: kustomize5
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
