apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pool-webapp
spec:
  generators:
    - git:
        repoURL: https://github.com/Viva-con-Agua/pool-webapp-deploy.git
        revision: HEAD
        directories:
          - path: "*"
  template:
    metadata:
      name: "pool-webapp-{{path}}"
    spec:
      destination:
        name: in-cluster
      project: "vca-{{path}}"
      source:
        repoURL: https://github.com/Viva-con-Agua/pool-webapp-deploy.git
        targetRevision: HEAD
        path: "{{path}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
