apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pool-api
spec:
  generators:
    - git:
        repoURL: https://github.com/Viva-con-Agua/pool-api-deploy.git
        revision: HEAD
        directories:
          - path: "*"
  template:
    metadata:
      name: "pool-api-{{path}}"
    spec:
      destination:
        name: in-cluster
      project: "vca-{{path}}"
      source:
        repoURL: https://github.com/Viva-con-Agua/pool-api-deploy.git
        targetRevision: HEAD
        path: "{{path}}"
        kustomize:
          version: kustomize5
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
