apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: web-components
spec:
  generators:
    - git:
        repoURL: https://github.com/Viva-con-Agua/web-components-deploy.git
        revision: HEAD
        directories:
          - path: "*"
  template:
    metadata:
      name: "web-components-{{path}}"
    spec:
      destination:
        name: in-cluster
      project: "vca-{{path}}"
      source:
        repoURL: https://github.com/Viva-con-Agua/web-components-deploy.git
        targetRevision: HEAD
        path: "{{path}}"
      resourceExclusions:
        - group: networking.k8s.io
          kind: Ingress
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
